services:
    server1:
        restart: always
        build:
            context: ./
            target: backend-dev
        volumes:
            - ./:/usr/local/app
        depends_on:
            - mongo
            - rabbitmq
            - redis
        environment:
            PORT: 8000
            MONGO_URL: mongodb://mongo:27017/vibetalk
            SERVER_SELECTION_TIMEOUT_MS: 5000
            RABBITMQ_URL: amqp://rabbitmq:5672
            REDIS_URL: redis://redis:6379
    server2:
        restart: always
        build:
            context: ./
            target: backend-dev
        volumes:
            - ./:/usr/local/app
        depends_on:
            - mongo
            - rabbitmq
            - redis
        environment:
            PORT: 8000
            MONGO_URL: mongodb://mongo:27017/vibetalk
            SERVER_SELECTION_TIMEOUT_MS: 5000
            RABBITMQ_URL: amqp://rabbitmq:5672
            REDIS_URL: redis://redis:6379

    mongo:
        image: mongo:7.0-jammy
        command: --logpath /dev/null
        restart: always
        volumes:
            - vibetalk-data:/data/db
        ports:
            - 27017:27017

    rabbitmq:
        image: rabbitmq:4.0-management-alpine
        logging:
            driver: "none"
        environment:
            - RABBITMQ_FEATURE_FLAGS=khepri_db
        ports:
            - "5672:5672"
            - "15672:15672"
    redis:
        image: redis/redis-stack:latest
        ports:
            - "6379:6379"
            - "8001:8001"
    nginx:
        image: nginx:stable-alpine
        volumes:
            - ./nginx/nginx.conf:/etc/nginx/nginx.conf:ro
        ports:
            - "8000:80"
        depends_on:
            - server1
            - server2
    prometheus:
        image: prom/prometheus
        volumes:
            - ./prometheus/prometheus.yml:/etc/prometheus/prometheus.yml
        ports:
            - "9090:9090"
volumes:
    vibetalk-data:
